spring:
  application:
    name: qs-gateway-service
  config:
    import: nacos:qs-gateway-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml



