spring:
  application:
    name: qs-gateway-service
  profiles:
    active: dev
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        file-extension: yml
        refresh-enabled: true
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
