export const STATUS_CODES = {
  SUCCESS: 200,
  ERROR: 500,
  PARAM_ERROR: 400,
  NO_PERMISSION: 403,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401
};

export const QR_CODE_STATUS = {
  ACTIVE: 'ACTIVE',
  INVALID: 'INVALID',
  FROZEN: 'FROZEN',
  CANCELLED: 'CANCELLED'
};

export const BATCH_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const ALERT_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
};