spring:
#  server:(nacos上的配置文件里设置了端口，这里注释掉，避免冲突)
#    port: 8081
  application:
    name: qs-auth-service
  profiles:
    active: dev
  config:
    import: optional:nacos:qs-auth-service-${spring.profiles.active}.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  datasource:
    url: jdbc:mysql://localhost:3306/yx_company_auth
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
